//! Generation step systems.
pub mod build_cities;
pub mod cities;
pub mod elevated;
pub mod finalize;
pub mod forest_trailheads;
pub mod forest_trails;
pub mod forests;
pub mod highway;
pub mod highway_interchanges;
pub mod init_base;
pub mod lakes;
pub mod mongroups;
pub mod mutable_specials;
pub mod neighbor_connections;
pub mod oceans;
pub mod radios;
pub mod railroads;
pub mod ravines;
pub mod rivers;
pub mod roads;
pub mod specials;
pub mod stubs;
pub mod subway;
pub mod swamps;

pub use build_cities::build_cities;
pub use cities::{calculate_urbanity, place_cities, CityTiles};
pub use elevated::generate_over;
pub use finalize::finalize_overmap;
pub use forest_trailheads::place_forest_trailheads;
pub use forest_trails::place_forest_trails;
pub use forests::{calculate_forestosity, place_forests};
pub use highway::place_highways;
pub use highway_interchanges::{finalize_highways, place_highway_interchanges};
pub use init_base::init_base_terrain;
pub use lakes::place_lakes;
pub use mongroups::{place_mongroups, MonsterGroup};
pub use mutable_specials::{place_mutable_specials, PlacedMutableSpecial};
pub use neighbor_connections::{populate_connections_out_from_neighbors, ConnectionExits};
pub use oceans::{calculate_ocean_gradient, place_oceans};
pub use radios::{place_radios, RadioTower};
pub use railroads::place_railroads;
pub use ravines::place_ravines;
pub use rivers::{build_river_shores, place_rivers, polish_river};
pub use roads::place_roads;
pub use specials::{place_specials, PlacedSpecial};
pub use stubs::generate_shore_variants;
pub use subway::generate_sub;
pub use swamps::place_swamps;
