[package]
name = "cdda_app"
version = "0.1.0"
edition = "2021"
description = "Binary entry point – App::new() + plugin registration."

[[bin]]
name = "cdda"
path = "src/main.rs"

[dependencies]
cdda_render.workspace = true
cdda_input.workspace = true
cdda_sim.workspace = true
cdda_core.workspace = true
cdda_screen.workspace = true
cdda_replay  = { path = "../cdda_replay" }
cdda_actor   = { path = "../cdda_actor" }
cdda_item    = { path = "../cdda_item" }
cdda_assets  = { path = "../cdda_assets" }
bevy = { workspace = true, features = ["3d"] }
bevy-inspector-egui.workspace = true
bevy_egui = { version = "0.39" }
bevy_state = "0.18"
tracing.workspace = true

[features]
default = ["dynamic"]
dynamic = ["bevy/dynamic_linking"]

[dev-dependencies]
