[package]
name = "cdda_combat"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs.workspace = true
bevy_reflect.workspace = true
bevy_app.workspace = true
cdda_core_types = { path = "../cdda_core_types" }
cdda_components = { path = "../cdda_components" }

[dev-dependencies]
cdda_sim = { path = "../cdda_sim" }
cdda_data = { path = "../cdda_data" }
