//! Game definition types — each module maps to one or more JSON `"type"` values.
//!
//! These structs are the typed representations of CDDA's JSON data definitions.
//! They are populated by `crate::data::loader` and resolved by `crate::data::resolve`.

pub mod achievement;
pub mod activity_type;
pub mod addiction_type;
pub mod ammo_effect;
pub mod ammunition_type;
pub mod anatomy;
pub mod ascii_art;
pub mod attack_vector;
pub mod bash_damage_profile;
pub mod bionic;
pub mod body_graph;
pub mod body_part;
pub mod butchery_requirement;
pub mod camp_migration;
pub mod cdda_types;
pub mod character_mod;
pub mod charge_removal_blacklist;
pub mod city_building;
pub mod climbing_aid;
pub mod clothing_mod;
pub mod conduct;
pub mod connect_group;
pub mod construction;
pub mod construction_category;
pub mod construction_group;
pub mod damage_info_order;
pub mod damage_type;
pub mod disease_type;
pub mod dream;
pub mod effect;
pub mod effect_on_condition;
pub mod emit;
pub mod end_screen;
pub mod event_statistic;
pub mod event_transformation;
pub mod faction;
pub mod faction_mission;
pub mod fault;
pub mod fault_fix;
pub mod fault_group;
pub mod field;
pub mod forest_biome_component;
pub mod forest_biome_mapgen;
pub mod furniture;
pub mod gate;
pub mod harvest;
pub mod harvest_drop_type;
pub mod hit_range;
pub mod item;
pub mod item_action;
pub mod item_category;
pub mod item_group;
pub mod item_migration;
pub mod jmath_function;
pub mod json_flag;
pub mod limb_score;
pub mod map_extra;
pub mod map_extra_collection;
pub mod mapgen;
pub mod martial_art;
pub mod material;
pub mod mission_definition;
pub mod monster;
pub mod monster_attack;
pub mod monster_blacklist;
pub mod monster_faction;
pub mod monster_flag;
pub mod monstergroup;
pub mod mood_face;
pub mod morale_type;
pub mod movement_mode;
pub mod mutation;
pub mod mutation_type;
pub mod nested_category;
pub mod npc;
pub mod npc_class;
pub mod omt_placeholder;
pub mod oter_id_migration;
pub mod oter_vision;
pub mod overlay_order;
pub mod overmap_terrain;
pub mod pp_generator;
pub mod practice;
pub mod profession;
pub mod profession_group;
pub mod profession_item_substitutions;
pub mod proficiency;
pub mod proficiency_category;
pub mod proficiency_migration;
pub mod recipe;
pub mod recipe_category;
pub mod recipe_group;
pub mod region_settings;
pub mod region_settings_terrain_furniture;
pub mod region_terrain_furniture;
pub mod relic_procgen_data;
pub mod requirement;
pub mod rotatable_symbol;
pub mod scenario;
pub mod scenario_blacklist;
pub mod scent_type;
pub mod score;
pub mod shopkeeper_blacklist;
pub mod shopkeeper_consumption_rates;
pub mod skill;
pub mod skill_display_type;
pub mod snippet;
pub mod species;
pub mod speech;
pub mod speed_description;
pub mod spell;
pub mod start_location;
pub mod sub_body_part;
pub mod talk_topic;
pub mod technique;
pub mod temperature_removal_blacklist;
pub mod ter_furn_migration;
pub mod ter_furn_transform;
pub mod terrain;
pub mod tool_quality;
pub mod trait_migration;
pub mod trap;
pub mod trap_migration;
pub mod uncraft;
pub mod var_migration;
pub mod vehicle_def;
pub mod vehicle_part;
pub mod vehicle_part_migration;
pub mod vehicle_placement;
pub mod vehicle_spawn;
pub mod vitamin;
pub mod weakpoint_set;
pub mod weapon_category;
pub mod weather_generator;
pub mod weather_type;
pub mod widget;

pub use cdda_types::*;

// Re-exports for convenience
pub use achievement::AchievementDef;
pub use activity_type::ActivityTypeDef;
pub use addiction_type::AddictionTypeDef;
pub use ammo_effect::AmmoEffectDef;
pub use ammunition_type::AmmunitionTypeDef;
pub use anatomy::AnatomyDef;
pub use ascii_art::AsciiArtDef;
pub use attack_vector::AttackVectorDef;
pub use bash_damage_profile::BashDamageProfileDef;
pub use bionic::{BionicDef, BionicGroupDef};
pub use body_graph::BodyGraphDef;
pub use body_part::BodyPartDef;
pub use butchery_requirement::ButcheryRequirementDef;
pub use camp_migration::CampMigrationDef;
pub use character_mod::CharacterModDef;
pub use charge_removal_blacklist::ChargeRemovalBlacklistDef;
pub use city_building::{CityBuildingDef, CityBuildingOvermap};
pub use climbing_aid::ClimbingAidDef;
pub use clothing_mod::ClothingModDef;
pub use conduct::ConductDef;
pub use connect_group::ConnectGroupDef;
pub use construction::{ConstructionByproduct, ConstructionDef};
pub use construction_category::ConstructionCategoryDef;
pub use construction_group::ConstructionGroupDef;
pub use damage_info_order::DamageInfoOrderDef;
pub use damage_type::DamageTypeDef;
pub use disease_type::DiseaseTypeDef;
pub use dream::DreamDef;
pub use effect::EffectDef;
pub use effect_on_condition::EffectOnConditionDef;
pub use emit::EmitDef;
pub use end_screen::EndScreenDef;
pub use event_statistic::EventStatisticDef;
pub use event_transformation::EventTransformationDef;
pub use faction::FactionDef;
pub use faction_mission::FactionMissionDef;
pub use fault::FaultDef;
pub use fault_fix::FaultFixDef;
pub use fault_group::FaultGroupDef;
pub use field::FieldDef;
pub use forest_biome_component::ForestBiomeComponentDef;
pub use forest_biome_mapgen::ForestBiomeMapgenDef;
pub use furniture::FurnitureDef;
pub use gate::GateDef;
pub use harvest::{HarvestDef, HarvestEntry};
pub use harvest_drop_type::HarvestDropTypeDef;
pub use hit_range::HitRangeDef;
pub use item::{CountMode, ItemDef, PocketDef, PocketType};
pub use item_action::ItemActionDef;
pub use item_category::ItemCategoryDef;
pub use item_group::{ItemGroupDef, ItemGroupEntry, ItemGroupSubtype};
pub use item_migration::ItemMigrationDef;
pub use jmath_function::JmathFunctionDef;
pub use json_flag::JsonFlagDef;
pub use limb_score::LimbScoreDef;
pub use map_extra::MapExtraDef;
pub use map_extra_collection::MapExtraCollectionDef;
pub use mapgen::{
    MapgenDef, MapgenObject, MapgenPaletteDef, MapgenTarget, PaletteRef, PlaceField,
    PlaceFurniture, PlaceItem, PlaceLoot, PlaceMonster, PlaceNested, PlaceNpc, PlaceTerrain,
    PlaceTrap, PlaceVehicle, PlaceZone, PosOrRange, SetDirective,
};
pub use martial_art::{MartialArtBuff, MartialArtDef};
pub use material::MaterialDef;
pub use mission_definition::MissionDefinitionDef;
pub use monster::MonsterDef;
pub use monster_attack::MonsterAttackDef;
pub use monster_blacklist::MonsterBlacklistDef;
pub use monster_faction::MonsterFactionDef;
pub use monster_flag::MonsterFlagDef;
pub use monstergroup::{MonsterGroupDef, MonsterGroupEntry};
pub use mood_face::{MoodFaceDef, MoodFaceValue};
pub use morale_type::MoraleTypeDef;
pub use movement_mode::MovementModeDef;
pub use mutation::{MutationCategoryDef, MutationDef, TraitGroupDef};
pub use mutation_type::MutationTypeDef;
pub use nested_category::NestedCategoryDef;
pub use npc::NpcDef;
pub use npc_class::NpcClassDef;
pub use omt_placeholder::OmtPlaceholderDef;
pub use oter_id_migration::OterIdMigrationDef;
pub use oter_vision::OterVisionDef;
pub use overlay_order::OverlayOrderDef;
pub use overmap_terrain::{
    OvermapConnectionDef, OvermapLandUseCodeDef, OvermapLocationDef, OvermapSpecialDef,
    OvermapTerrainDef,
};
pub use pp_generator::PpGeneratorDef;
pub use practice::{PracticeData, PracticeDef};
pub use profession::ProfessionDef;
pub use profession_group::ProfessionGroupDef;
pub use profession_item_substitutions::ProfessionItemSubstitutionsDef;
pub use proficiency::ProficiencyDef;
pub use proficiency_category::ProficiencyCategoryDef;
pub use proficiency_migration::ProficiencyMigrationDef;
pub use recipe::RecipeDef;
pub use recipe_category::RecipeCategoryDef;
pub use recipe_group::{RecipeGroupDef, RecipeGroupEntry};
pub use region_settings::RegionSettingsDef;
pub use region_settings_terrain_furniture::RegionSettingsTerrainFurnitureDef;
pub use region_terrain_furniture::RegionTerrainFurnitureDef;
pub use relic_procgen_data::RelicProcgenDataDef;
pub use requirement::RequirementDef;
pub use rotatable_symbol::RotatableSymbolDef;
pub use scenario::ScenarioDef;
pub use scenario_blacklist::ScenarioBlacklistDef;
pub use scent_type::ScentTypeDef;
pub use score::ScoreDef;
pub use shopkeeper_blacklist::ShopkeeperBlacklistDef;
pub use shopkeeper_consumption_rates::ShopkeeperConsumptionRatesDef;
pub use skill::SkillDef;
pub use skill_display_type::SkillDisplayTypeDef;
pub use snippet::SnippetDef;
pub use species::SpeciesDef;
pub use speech::SpeechDef;
pub use speed_description::SpeedDescriptionDef;
pub use spell::SpellDef;
pub use start_location::StartLocationDef;
pub use sub_body_part::SubBodyPartDef;
pub use talk_topic::{TalkResponse, TalkResult, TalkTopicDef, TalkTrial};
pub use technique::{SkillRequirement, TechEffect, TechniqueBonus, TechniqueDef};
pub use temperature_removal_blacklist::TemperatureRemovalBlacklistDef;
pub use ter_furn_migration::TerFurnMigrationDef;
pub use ter_furn_transform::TerFurnTransformDef;
pub use terrain::TerrainDef;
pub use tool_quality::ToolQualityDef;
pub use trait_migration::TraitMigrationDef;
pub use trap::TrapDef;
pub use trap_migration::TrapMigrationDef;
pub use uncraft::{QualReq, UncraftDef};
pub use var_migration::VarMigrationDef;
pub use vehicle_def::{VehicleBlueprintPart, VehicleDef, VehicleItemSpawn};
pub use vehicle_part::{VehiclePartCategoryDef, VehiclePartDef, VehiclePartLocationDef};
pub use vehicle_part_migration::VehiclePartMigrationDef;
pub use vehicle_placement::VehiclePlacementDef;
pub use vehicle_spawn::VehicleSpawnDef;
pub use vitamin::VitaminDef;
pub use weakpoint_set::{Weakpoint, WeakpointEffect, WeakpointSetDef};
pub use weapon_category::WeaponCategoryDef;
pub use weather_generator::WeatherGeneratorDef;
pub use weather_type::WeatherTypeDef;
pub use widget::{WidgetClause, WidgetDef};
